name: first workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: print greeting
        run: echo "Hello test message"
      - name: print goodbye
        run: echo " done - goodbye"
